---
name: "ExtraAuthSettings"
guid: "0e1e569f-1060-4115-a35d-a9886e393725"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "A few extra settings for authentication/authorization of users."
imageUrl: "https://raw.githubusercontent.com/BananaBagel/jellyfin-ExtraAuthSettings/main/style/card.svg"
description: >
  This plugin adds a few extra settings for authentication/authorization of users.
  It is not a replacement for the built in authentication system,
  but rather a way to add a few extra features that are not currently available.
category: "Administration"
owner: "BananaBagel"
artifacts:
  - "ExtraAuthSettings.dll"
changelog: >
  changelog
